### ISSUE TITLE
Отправка данных

### ISSUE THREAD

**Issue by KroTNR** [fredbay/techdemo#69]
![image](https://user-images.githubusercontent.com/52551883/75630643-b3d29f80-5bfd-11ea-8444-db0744622da9.png)

**Comment by iRebbok** [comment]
Заменяется #72, это закрываю.

**Comment by maxp** [comment]
Уважаемые!

Деалайте issue понятными другим людям, а не в виде ребуса - "что тут имел ввиду автор?".

Схемы есть смыл делать, когда на них много элементов со сложными связями. Для списка из 4 последовательных действий картинка только мешает.
